### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by leafseelight** [Coolpy7/coolpy7_benchmark#5]
2021/06/20 17:43:17 callback read tcp 172.18.88.182:10641->47.107.80.67:1883: read: connection reset by peer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x724b3d]

goroutine 3011 [running]:
main.main.func1(0x0, 0x81b160, 0xc0012f45f0, 0x0, 0x0)
        D:/GolandProjects/coolpy7_benchmark/test_bench_sub/cp7_bench_sub.go:39 +0x12d
client.(*Client).die.func1()
        D:/GolandProjects/coolpy7_benchmark/src/client/client.go:848 +0xfa
sync.(*Once).Do(0xc001522c18, 0xc001544da8)
        C:/Go/src/sync/once.go:44 +0xd1
client.(*Client).die(0xc001522b60, 0x81b160, 0xc0012f45f0, 0x810000, 0x0, 0x0)
        D:/GolandProjects/coolpy7_benchmark/src/client/client.go:844 +0xa3
client.(*Client).processor(0xc001522b60, 0x0, 0x0)

**Comment by leafseelight** [comment]
前面的日志是
2021/06/20 17:00:41 12 192.168.77.22
2021/06/20 17:00:41 13 192.168.77.23
2021/06/20 17:00:41 14 192.168.77.24
2021/06/20 17:00:41 15 192.168.77.25
2021/06/20 17:00:41 16 192.168.77.26
2021/06/20 17:00:41 17 192.168.77.27
2021/06/20 17:00:41 18 192.168.77.28
2021/06/20 17:00:41 19 192.168.77.29
2021/06/20 17:00:41 20 192.168.77.30
2021/06/20 17:00:41 0
2021/06/20 17:02:48 1 change local address
2021/06/20 17:04:55 2 change local address
2021/06/20 17:07:03 3 change local address
2021/06/20 17:09:10 4 change local address
2021/06/20 17:11:17 5 change local address
2021/06/20 17:13:24 6 change local address
2021/06/20 17:15:32 7 change local address
2021/06/20 17:17:39 8 change local address
2021/06/20 17:19:46 9 change local address
2021/06/20 17:21:53 10 change local address
2021/06/20 17:24:01 11 change local address
2021/06/20 17:26:08 12 change local address
2021/06/20 17:28:15 13 change local address
2021/06/20 17:30:22 14 change local address
2021/06/20 17:32:30 15 change local address
2021/06/20 17:34:37 16 change local address
2021/06/20 17:36:44 17 change local address
2021/06/20 17:38:51 18 change local address
2021/06/20 17:40:58 19 change local address
2021/06/20 17:43:06 20 change local address

**Comment by jacoblai** [comment]
你的路由器不是192.168.77的吧？创创虚拟ip的时候，要按你当前交换机或路由器的ip的前三段一致。然后再确认有哪些空闲的，没有被其他同一路由器下的设备占用的ip进行创建虚拟ip。
